# Generated by Django 4.0 on 2025-01-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('amount_of_water_used', models.FloatField()),
                ('number_of_people_using_water', models.IntegerField()),
                ('number_of_livestock_using_water', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CapacityBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_trainings', models.IntegerField()),
                ('number_of_people_trained', models.IntegerField()),
                ('modules_covered', models.TextField()),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FarmersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HayStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_of_hay', models.FloatField()),
                ('number_of_bales_stored', models.IntegerField()),
                ('number_of_bales_given_sold', models.IntegerField()),
                ('revenue_made', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('affected_livestock_count', models.IntegerField()),
                ('treatment_provided', models.TextField()),
                ('vaccination_preventive_measures', models.TextField()),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price_trends', models.TextField()),
                ('supply_and_demand_analysis', models.TextField()),
                ('weekly_transactions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LivestockFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_goats', models.IntegerField()),
                ('male_goats', models.IntegerField()),
                ('female_goats', models.IntegerField()),
                ('goats_1_6_months', models.IntegerField()),
                ('weight_1_7_kgs', models.IntegerField()),
                ('weekly_goats_sold', models.IntegerField()),
                ('amount_paid_to_farmer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sold', models.DateField()),
                ('vaccination_schedule', models.TextField()),
                ('deworming_schedule', models.DateField()),
                ('breeding_info', models.TextField()),
                ('traceability_system', models.TextField()),
                ('farmer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.farmersdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FodderFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_acreage_for_fodder', models.FloatField()),
                ('leased', models.BooleanField()),
                ('sharing_model', models.TextField()),
                ('groups_associated', models.CharField(max_length=255)),
                ('group_members_count', models.IntegerField()),
                ('total_hectares_under_pastures', models.FloatField()),
                ('yield_per_harvest', models.FloatField()),
                ('region', models.CharField(max_length=255)),
                ('farmer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.farmersdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=255)),
                ('fodder_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.fodderfarmer')),
                ('livestock_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.livestockfarmer')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borehole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.borehole')),
                ('hay_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.haystorage')),
                ('livestock_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.livestockfarmer')),
            ],
        ),
    ]
