# Generated by Django 4.0 on 2025-01-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_capacitybuilding_date_farmerinfrastructure_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst')], default='analyst', max_length=10)),
            ],
        ),
    ]
