# Generated by Django 4.0 on 2025-01-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('water_used', models.FloatField(default=0.0)),
                ('people_using_water', models.PositiveIntegerField(default=0)),
                ('livestock_using_water', models.PositiveIntegerField(default=0)),
                ('bales_stored', models.PositiveIntegerField(default=0)),
                ('hay_size', models.FloatField(default=0.0)),
                ('bales_given_or_sold', models.PositiveIntegerField(default=0)),
                ('revenue_made', models.FloatField(default=0.0)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LivestockDisease',
        ),
        migrations.DeleteModel(
            name='MarketData',
        ),
        migrations.RemoveField(
            model_name='farmerinfrastructure',
            name='hay_storage',
        ),
        migrations.DeleteModel(
            name='HayStorage',
        ),
        migrations.AlterField(
            model_name='farmerinfrastructure',
            name='borehole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.infrastructure'),
        ),
        migrations.DeleteModel(
            name='Borehole',
        ),
    ]
